### ISSUE TITLE
"Invalid value given to chunkConfigs option"

### ISSUE THREAD

**Issue by rowild** [architgarg/html-webpack-injector#8]
@thearchitgarg Hi, it's me again :-)

In my configuration, I want to assign `defer` to a script and therefore use `chunkConfig` as recommended in the Readme. But in doing so, the terminal tells me `Invalid value given to chunkConfigs option` (screenshot added).

What am I missing?

This is a snippet of my configuration:

```javascript
  [...]
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './src/templates/index.ejs',
      chunks: ['app_head', 'vendor_head', 'startpage'],
      chunksConfig: {
        defer: ['startpage']
      },
      excludeChunks: ['subpage'],
      [...]
  },
  new HtmlWebpackInjector()
  [...]
```

![Screen Shot 2020-05-08 at 11 09 15](https://user-images.githubusercontent.com/213803/81390851-6fdba980-911c-11ea-9cc5-cf03fedd51da.png)

**Comment by thearchitgarg** [comment]
Hey, I am sorry that it caused you inconvenience. Just pass this, it would work. 

```js
  chunksConfig: {
        defer: ['startpage'],
        async: []
      }
```

**Comment by rowild** [comment]
Wow, that was fast! Thank you!

I agree: defining both params, even though I might only need one, is weird / confusing. Would be worth mentioning it in the readme or, even better, handle it automatically.

Do you want me to leave this issue open or not?

Thank you again!!!

**Comment by thearchitgarg** [comment]
Keep it open. I will handle this thing internally and close this issue. Thanks ;)
